# Generated by Django 3.2.2 on 2021-05-12 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klaim_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataklaim',
            options={'verbose_name': 'DATA KLAIM', 'verbose_name_plural': 'LIST DATA KLAIM'},
        ),
        migrations.AlterModelOptions(
            name='perusahaan',
            options={'ordering': ['-npp'], 'verbose_name': 'NPP', 'verbose_name_plural': 'LIST NPP'},
        ),
        migrations.CreateModel(
            name='DaftarHRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klaim_registration.perusahaan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LIST HRD',
            },
        ),
    ]
