# Generated by Django 3.2.2 on 2021-05-13 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klaim_registration', '0002_auto_20210513_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataklaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
