# Generated by Django 3.2.2 on 2021-05-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0004_auto_20210513_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalhrd',
            name='status',
            field=models.CharField(choices=[('DALAM PEMERIKSAAN', 'DALAM PEMERIKSAAN'), ('DISETUJUI', 'DISETUJUI'), ('DITOLAK', 'DITOLAK')], default='DALAM PEMERIKSAAN', max_length=20),
        ),
    ]
