# Generated by Django 3.2.2 on 2021-05-17 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klaim_registration', '0005_alter_approvalhrd_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataklaim',
            name='no_hp',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,9})$', 'Format NO HP TIDAK SESUA!!!')]),
        ),
    ]
